import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import Link from "next/link";
// لو عندك مكون اللوجو اللي عملناه، تقدر تستدعيه هنا
// import { Logo } from "@/components/Logo";

export default async function LandingPage() {
  // 1. التحقق من تسجيل الدخول (لو مسجل، حوله للمواد فوراً)
    const { userId } = await auth();
      if (userId) {
          redirect("/dashboard"); // أو المسار الخاص بالداشبورد عندك
            }

              // 2. لو مش مسجل دخول، اعرض صفحة الهبوط
                return (
                    <div className="min-h-screen bg-[#0a0a0a] text-white selection:bg-cyan-500/30">
                          {/* الشريط العلوي (Navbar) */}
                                <nav className="border-b border-white/10 bg-black/50 backdrop-blur-md fixed top-0 w-full z-50">
                                        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
                                                  <div className="flex items-center gap-2 font-bold text-xl">
                                                              {/* <Logo className="w-8 h-8" /> */} {/* شيل الكومنت لو حطيت اللوجو */}
                                                                          <span className="text-white">Eng<span className="text-cyan-500">Tracker</span></span>
                                                                                    </div>
                                                                                              <div className="flex gap-4">
                                                                                                          <Link 
                                                                                                                        href="/sign-in" 
                                                                                                                                      className="px-4 py-2 text-sm font-medium text-gray-300 hover:text-white transition"
                                                                                                                                                  >
                                                                                                                                                                تسجيل الدخول
                                                                                                                                                                            </Link>
                                                                                                                                                                                        <Link 
                                                                                                                                                                                                      href="/sign-up" 
                                                                                                                                                                                                                    className="px-4 py-2 text-sm font-medium bg-cyan-600 hover:bg-cyan-500 text-white rounded-lg transition"
                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                              حساب جديد
                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                  </nav>

                                                                                                                                                                                                                                                                                        {/* القسم الرئيسي (Hero Section) */}
                                                                                                                                                                                                                                                                                              <main className="pt-32 pb-16 px-6 max-w-7xl mx-auto text-center" dir="rtl">
                                                                                                                                                                                                                                                                                                      <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6">
                                                                                                                                                                                                                                                                                                                نظّم دراستك الهندسية <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500">بذكاء</span>
                                                                                                                                                                                                                                                                                                                        </h1>
                                                                                                                                                                                                                                                                                                                                <p className="text-gray-400 text-lg md:text-xl max-w-2xl mx-auto mb-10 leading-relaxed">
                                                                                                                                                                                                                                                                                                                                          المساعد الأول لطالب الهندسة. تتبع موادك، راقب نسبة إنجازك، واحصل على تنبيهات ذكية قبل مواعيد محاضراتك وسكاشنك.
                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
                                                                                                                                                                                                                                                                                                                                                                    <Link 
                                                                                                                                                                                                                                                                                                                                                                                href="/sign-up" 
                                                                                                                                                                                                                                                                                                                                                                                            className="px-8 py-4 text-lg font-bold bg-cyan-600 hover:bg-cyan-500 text-white rounded-xl transition shadow-[0_0_20px_rgba(6,182,212,0.3)] hover:shadow-[0_0_30px_rgba(6,182,212,0.5)]"
                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                  ابدأ الآن مجاناً
                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* قسم المميزات (Features) متماشي مع ستايل كروت الموقع */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-32 grid grid-cols-1 md:grid-cols-3 gap-6 text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* الكارت الأول */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="p-6 rounded-2xl border border-white/10 bg-[#111111] hover:border-cyan-500/50 transition duration-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="w-12 h-12 rounded-full bg-cyan-500/10 flex items-center justify-center mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <svg className="w-6 h-6 text-cyan-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-xl font-bold mb-2">إدارة المواد بسهولة</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-400 leading-relaxed">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              أضف موادك الدراسية، حدد عدد المحاضرات والسكاشن، ونظّم جدولك الأسبوعي في مكان واحد مخصص للمهندسين.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* الكارت الثاني */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-6 rounded-2xl border border-white/10 bg-[#111111] hover:border-cyan-500/50 transition duration-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="w-12 h-12 rounded-full bg-blue-500/10 flex items-center justify-center mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <svg className="w-6 h-6 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-xl font-bold mb-2">تتبع نسبة الإنجاز</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-gray-400 leading-relaxed">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    راقب تقدمك الأكاديمي من خلال دوائر إحصائية ذكية تعرض نسبة حضورك وإنجازك في كل مادة بشكل مرئي جذاب.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* الكارت الثالث */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="p-6 rounded-2xl border border-white/10 bg-[#111111] hover:border-cyan-500/50 transition duration-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="w-12 h-12 rounded-full bg-purple-500/10 flex items-center justify-center mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <svg className="w-6 h-6 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path></svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-xl font-bold mb-2">منبه سحابي ذكي</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-gray-400 leading-relaxed">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          لا تفوت أي محاضرة. نظامنا السحابي سيرسل لك إشعارات على متصفحك قبل مواعيدك بـ 15 و 30 دقيقة تلقائياً.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
